export interface CarWallpaper {
  id: string;
  title: string;
  slug: string;
  brand: string;
  category: 'Supercar' | 'Hypercar' | 'Classic' | 'Off-road' | 'Luxury' | 'JDM' | 'Motor Sport';
  imageUrl: string;
}
export interface PhoneWallpaper {
  id: string;
  title: string;
  slug: string;
  brand: string;
  category: string;
  imageUrl: string;
}

export const CAR_WALLPAPERS: CarWallpaper[] = [
  {
    id: '1',
    title: 'Bentley Mulliner',
    slug: 'bentley-mulliner',
    brand: 'Bentley',
    category: 'Luxury',
    imageUrl: '/images/bentley-mulliner-3840x2160-22211.jpg',
  },
  {
    id: '2',
    title: 'Bugatti Chiron',
    slug: 'bugatti-chiron',
    brand: 'Bugatti',
    category: 'Hypercar',
    imageUrl: '/images/bugatti-chiron-3840x2160-24117.jpg',
  },
  {
    id: '3',
    title: 'Ferrari 12Cilindri',
    slug: 'ferrari-12cilindri',
    brand: 'Ferrari',
    category: 'Supercar',
    imageUrl: '/images/ferrari-12cilindri-3840x2160-22230.jpg',
  },
  {
    id: '4',
    title: 'Ferrari 499P',
    slug: 'ferrari-499p-1',
    brand: 'Ferrari',
    category: 'Motor Sport',
    imageUrl: '/images/ferrari-499p-8k-7680x4320-19304.jpg',
  },
  {
    id: '5',
    title: 'Ferrari 499P',
    slug: 'ferrari-499p-2',
    brand: 'Ferrari',
    category: 'Motor Sport',
    imageUrl: '/images/ferrari-499p-2025-6016x3384-21449.jpg',
  },
  {
    id: '6',
    title: 'Porsche 911 GT3 RS',
    slug: 'porsche-911-gt3-rs-ultrawide',
    brand: 'Porsche',
    category: 'Supercar',
    imageUrl: '/images/Ultrawide_Wallpaper_5.jpg',
  },
  {
    id: '7',
    title: 'Mercedes G Wagon',
    slug: 'mercedes-g-wagon',
    brand: 'Mercedes',
    category: 'Off-road',
    imageUrl: '/images/g-wagon-mercedes-3840x2160-24405.jpg',
  },
  {
    id: '8',
    title: 'Mercedes G Wagon Black',
    slug: 'mercedes-g-wagon-black',
    brand: 'Mercedes',
    category: 'Off-road',
    imageUrl: '/images/IMG_3770.jpg',
  },
  {
    id: '9',
    title: 'Porsche 911 Carrera',
    slug: 'porsche-911-carrera-1',
    brand: 'Porsche',
    category: 'Supercar',
    imageUrl: '/images/porsche-911-carrera-3840x2160-23036.jpeg',
  },
  {
    id: '10',
    title: 'Porsche 911 Carrera',
    slug: 'porsche-911-carrera-2',
    brand: 'Porsche',
    category: 'Supercar',
    imageUrl: '/images/porsche-911-carrera-3840x2160-23841.jpg',
  },
  {
    id: '11',
    title: 'Rolls Royce Phantom',
    slug: 'rolls-royce-phantom',
    brand: 'Rolls Royce',
    category: 'Luxury',
    imageUrl: '/images/rolls-royce-phantom-3840x2160-24430.jpg',
  },
  {
    id: '12',
    title: 'Rolls Royce Spectre',
    slug: 'rolls-royce-spectre',
    brand: 'Rolls Royce',
    category: 'Luxury',
    imageUrl: '/images/rolls-royce-spectre-3840x2160-22749.jpg',
  },
  {
    id: '13',
    title: 'Mazda RX-7',
    slug: 'mazda-rx7',
    brand: 'Mazda',
    category: 'JDM',
    imageUrl: '/images/Wallpaper_1.png',
  },
  {
    id: '14',
    title: 'Audi e-tron GT',
    slug: 'audi-e-tron-gt',
    brand: 'Audi',
    category: 'Supercar',
    imageUrl: '/images/audi-e-tron-gt-3840x2160-22450.jpg',
  },
  {
    id: '15',
    title: 'Bentley Flying Spur',
    slug: 'bentley-flying-spur',
    brand: 'Bentley',
    category: 'Luxury',
    imageUrl: '/images/bentley-flying-spur-3840x2160-20009.jpg',
  },
  {
    id: '16',
    title: 'Porsche 911 GT3 RS',
    slug: 'porsche-911-gt3-rs',
    brand: 'Porsche',
    category: 'Supercar',
    imageUrl: '/images/Ultrawide_Wallpaper_1.jpg',
  },
  {
    id: '17',
    title: 'Honda NSX',
    slug: 'honda-nsx',
    brand: 'Honda',
    category: 'JDM',
    imageUrl: '/images/wallhaven-475yre.png',
  },
  {
    id: '18',
    title: 'Nissan Skyline',
    slug: 'nissan-skyline',
    brand: 'Nissan',
    category: 'JDM',
    imageUrl: '/images/wallhaven-xl9krl.png',
  },
  {
    id: '19',
    title: 'Mercedes AMG GT',
    slug: 'mercedes-amg-gt',
    brand: 'Mercedes',
    category: 'Supercar',
    imageUrl: '/images/Wallpaper_12.jpg',
  },
  {
    id: '20',
    title: 'Subaru BRZ',
    slug: 'subaru-brz',
    brand: 'Subaru',
    category: 'JDM',
    imageUrl: '/images/subaru-2vo52uatxk5dk31e.png',
  },
  {
    id: '21',
    title: 'Toyota AE86',
    slug: 'toyota-ae86',
    brand: 'Toyota',
    category: 'JDM',
    imageUrl: '/images/wallhaven-lmkgry.png',
  },
  {
    id: '22',
    title: 'Nissan Skyline R34',
    slug: 'nissan-skyline-r34',
    brand: 'Nissan',
    category: 'JDM',
    imageUrl: '/images/wallhaven-vgvjem.png',
  },
  {
    id: '23',
    title: 'Nissan 350Z',
    slug: 'nissan-350z',
    brand: 'Nissan',
    category: 'JDM',
    imageUrl: '/images/wallhaven-6ld2yl.png',
  },
  {
    id: '24',
    title: 'Pagani Zonda',
    slug: 'pagani-zonda1',
    brand: 'Pagani',
    category: 'Hypercar',
    imageUrl: '/images/2009-Pagani-Zonda-Cinque-Roadster-010-2160-scaled.jpg',
  },
  {
    id: '25',
    title: 'Packard Twelve',
    slug: 'packard-twelve1',
    brand: 'Packard',
    category: 'Classic',
    imageUrl: '/images/IMG_0984.jpg',
  },
  {
    id: '26',
    title: 'Koenigsegg Agera R',
    slug: 'koenigsegg-agera-r1',
    brand: 'Koenigsegg',
    category: 'Hypercar',
    imageUrl: '/images/IMG_1757.jpg',
  },
  {
    id: '27',
    title: 'Koenigsegg Agera',
    slug: 'koenigsegg-agera1',
    brand: 'Koenigsegg',
    category: 'Hypercar',
    imageUrl: '/images/IMG_1760.jpg',
  },
  {
    id: '28',
    title: 'Koenigsegg Agera RS',
    slug: 'koenigsegg-agera-rs1',
    brand: 'Koenigsegg',
    category: 'Hypercar',
    imageUrl: '/images/IMG_1762.jpg',
  },
  {
    id: '29',
    title: 'Lamborghini Countach',
    slug: 'lamborghini-countach-1',
    brand: 'Lamborghini',
    category: 'Supercar',
    imageUrl: '/images/wallhaven-g76jyd.png',
  },
  {
    id: '30',
    title: 'Ferrari F40',
    slug: 'ferrari-f40-1',
    brand: 'Ferrari',
    category: 'Supercar',
    imageUrl: '/images/Wallpaper_6.jpg',
  },
  {
    id: '31',
    title: 'Classic Porsche 911',
    slug: 'classic-porsche',
    brand: 'Porsche',
    category: 'Classic',
    imageUrl: '/images/wp11735123-porsche-old-wallpapers.jpg',
  },
  {
    id: '32',
    title: 'Porsche 911 4K',
    slug: 'porsche-911-4k',
    brand: 'Porsche',
    category: 'Supercar',
    imageUrl: '/images/wp12427975-porsche-911-4k-wallpapers.jpg',
  },
  {
    id: '33',
    title: 'Mazda RX-7',
    slug: 'mazda-rx-7-1',
    brand: 'Mazda',
    category: 'JDM',
    imageUrl: '/images/1849db1a32e761bcfeda767885f0bdc1.jpg',
  },
  {
    id: '34',
    title: 'Ferrari F430',
    slug: 'ferrari-f430-2',
    brand: 'Ferrari',
    category: 'Supercar',
    imageUrl: '/images/4231F0E0-7782-4253-9EC1-9EA7B64C405C.jpg',
  },
  {
    id: '35',
    title: 'Ferrari F430',
    slug: 'ferrari-f430-1',
    brand: 'Ferrari',
    category: 'Supercar',
    imageUrl: '/images/B819674F-12C0-4574-87E4-BC2B6E51A495.jpg',
  },
  {
    id: '36',
    title: 'Porsche 911 GT3 RS',
    slug: 'porsche-911-gt3-rs-1',
    brand: 'Porsche',
    category: 'Supercar',
    imageUrl: '/images/Desktop_Wallpaper_3.jpg',
  },
  {
    id: '37',
    title: 'Pagani Huayra',
    slug: 'pagani-huayra1',
    brand: 'Pagani',
    category: 'Hypercar',
    imageUrl: '/images/pagani.png',
  },
  {
    id: '38',
    title: 'Bmw M Motorsport Race Cars',
    slug: 'bmw-m-motorsport-race-cars-01',
    brand: 'BMW',
    category: 'Motor Sport',
    imageUrl: '/images/bmw-m-motorsport-race-cars-01-16x9.jpg',
  },
  {
    id: '39',
    title: 'Bmw M Wallpaper Bmw Hybrid V8 34 Front',
    slug: 'bmw-m-wallpaper-bmw-hybrid-v8-34-front',
    brand: 'BMW',
    category: 'Motor Sport',
    imageUrl: '/images/bmw-m-wallpaper-bmw-hybrid-v8-34-front-4k.jpg',
  },
  {
    id: '40',
    title: 'Bmw M Wallpaper Bmw Hybrid V8 Launch Side',
    slug: 'bmw-m-wallpaper-bmw-hybrid-v8-launch-side',
    brand: 'BMW',
    category: 'Motor Sport',
    imageUrl: '/images/bmw-m-wallpaper-bmw-hybrid-v8-launch-side-4k.jpg',
  },
  {
    id: '41',
    title: 'Bmw M4 Gt3 Evo',
    slug: 'bmw-m4-gt3-evo2',
    brand: 'BMW',
    category: 'Motor Sport',
    imageUrl: '/images/bmw-m4-gt3-evo-4k-05.jpg',
  },
  {
    id: '42',
    title: 'Bmw M4 Gt4 Evo',
    slug: 'bmw-m4-gt4-evo',
    brand: 'BMW',
    category: 'Motor Sport',
    imageUrl: '/images/bmw-m4-gt4-evo-4k-05.jpg',
  },
  {
    id: '43',
    title: 'Wallpaper BMW M Hybrid V8 Top Detroit 2K',
    slug: 'wallpaper-bmw-m-hybrid-v8-top-detroit-2k',
    brand: 'BMW',
    category: 'Motor Sport',
    imageUrl: '/images/Wallpaper_BMW_M_Hybrid_V8_top_Detroit_2K.jpg',
  }
];

export const CATEGORIES = ['All', 'Supercar', 'Hypercar', 'Classic', 'Off-road', 'Luxury', 'JDM', 'Motor Sport'] as const;
export const PHONE_WALLPAPERS: PhoneWallpaper[] = [
  {
  id: '1',
  title: 'Aston Martin DBS Superleggera',
  slug: 'aston-martin-dbs-superleggera-1',
  brand: 'Aston Martin',
  category: 'Grand Tourer',
  imageUrl: '2f04f9360f50634c0b2398973b60445e.jpg',
},
{
  id: '2',
  title: 'Lamborghini Countach',
  slug: 'lamborghini-countach-2',
  brand: 'Lamborghini',
  category: 'Supercar',
  imageUrl: '8wyl2p.png',
},
{
  id: '3',
  title: 'Porsche 911',
  slug: 'porsche-911-3',
  brand: 'Porsche',
  category: 'Sports Car',
  imageUrl: '52e581ae1e16d933659c7bc092555ccc.jpg',
},
{
  id: '4',
  title: 'Subaru Impreza WRX STI',
  slug: 'subaru-impreza-wrx-sti-4',
  brand: 'Subaru',
  category: 'JDM Sports Sedan',
  imageUrl: '141496ad5b17f103bbc5c08b770a105b.png',
},
{
  id: '5',
  title: 'Aston Martin DB5',
  slug: 'aston-martin-db5-5',
  brand: 'Aston Martin',
  category: 'Classic Grand Tourer',
  imageUrl: 'a007bd6c219f1d63d87c4ff499c8efd0.jpg',
},
{
  id: '6',
  title: 'Porsche 911 GT1',
  slug: 'porsche-911-gt1-6',
  brand: 'Porsche',
  category: 'Race-derived Supercar',
  imageUrl: 'ac999dfd071ec4a5ce48b98acf382a14.jpg',
},
{
  id: '7',
  title: 'Subaru Impreza WRX STI',
  slug: 'subaru-impreza-wrx-sti-7',
  brand: 'Subaru',
  category: 'JDM Sports Sedan',
  imageUrl: 'HD-wallpaper-subaru-sti-wrx-car-cars-cool.png',
},
{
  id: '8',
  title: 'Audi RS6 Avant',
  slug: 'audi-rs6-avant-8',
  brand: 'Audi',
  category: 'Performance Wagon',
  imageUrl: 'IMG_0822.jpg',
},
{
  id: '9',
  title: 'Audi RS6 Avant',
  slug: 'audi-rs6-avant-9',
  brand: 'Audi',
  category: 'Performance Wagon',
  imageUrl: 'IMG_0823.jpg',
},
{
  id: '10',
  title: 'Audi RS6 Avant',
  slug: 'audi-rs6-avant-10',
  brand: 'Audi',
  category: 'Performance Wagon',
  imageUrl: 'IMG_0826.jpg',
},
{
  id: '11',
  title: 'Koenigsegg Jesko',
  slug: 'koenigsegg-jesko-11',
  brand: 'Koenigsegg',
  category: 'Hypercar',
  imageUrl: 'IMG_0827.jpg',
},
{
  id: '12',
  title: 'Lamborghini Countach',
  slug: 'lamborghini-countach-12',
  brand: 'Lamborghini',
  category: 'Classic Supercar',
  imageUrl: 'IMG_1348.jpg',
},
{
  id: '13',
  title: 'Chevrolet Corvette',
  slug: 'chevrolet-corvette-13',
  brand: 'Chevrolet',
  category: 'American Sports Car',
  imageUrl: 'IMG_2964.jpg',
},
{
  id: '14',
  title: 'BMW M3',
  slug: 'bmw-m3-14',
  brand: 'BMW',
  category: 'Classic Sports Sedan',
  imageUrl: 'IMG_3501.jpg',
},
{
  id: '15',
  title: 'Formula E Gen3',
  slug: 'formula-e-gen3-15',
  brand: 'Formula E',
  category: 'Electric Formula Race Car',
  imageUrl: 'IMG_6481.jpg',
},
{
  id: '16',
  title: 'BMW M3',
  slug: 'bmw-m3-16',
  brand: 'BMW',
  category: 'Classic Sports Sedan',
  imageUrl: 'IMG_8431.jpg',
},
{
  id: '17',
  title: 'BMW M3',
  slug: 'bmw-m3-17',
  brand: 'BMW',
  category: 'Classic Sports Sedan',
  imageUrl: 'IMG_9912.jpg',
},
{
  id: '18',
  title: 'Toyota Supra',
  slug: 'toyota-supra-18',
  brand: 'Toyota',
  category: 'JDM Sports Car',
  imageUrl: 'IMG_9913.jpg',
},
{
  id: '19',
  title: 'Subaru WRX STI',
  slug: 'subaru-wrx-sti-19',
  brand: 'Subaru',
  category: 'JDM Sports Sedan',
  imageUrl: 'wp9046408.jpg',
}
  ];
